---
title: "{{< var department >}} {{< var number >}}: {{< var name >}}"
subtitle: "UC Berkeley, {{< var semester >}}"
listing:
  - id: schedule
    template: assets/schedule.ejs
    contents: schedule.yml
---

Stat 210A is an introductory Ph.D.-level course in theoretical statistics. It is a fast-paced and demanding course intended to prepare students for research careers in statistics.

::: callout-important
## Course enrollment for undergraduates

If you are an undergraduate who wants to take this course, please fill out the [permission code request form](https://docs.google.com/forms/d/e/1FAIpQLSeykCsfaNmXnN0lFVzlR0B6PyvXbN_VMjHg_-owjaW9tmSlqA/viewform?usp=header) to let me know about your background. If you are unsure of your background, you can check the [frequently asked questions](faq.qmd) regarding preparation and review materials.
:::

## Resources

-   [Syllabus](syllabus.qmd) for basic course information
-   [Gradescope](https://www.gradescope.com/courses/1355311) for turning in homework
-   [EdStem](https://edstem.org/us/courses/101895/) for announcements and technical discussion (no homework spoilers!)
-   [bCourses](https://bcourses.berkeley.edu/courses/1557687) for lecture videos and homework solutions

## Schedule

::: {#schedule}
:::
