---
title: "Syllabus"
---

## Course information

### Instructors

-   **Primary Instructor** [Will Fithian](http://www.stat.berkeley.edu/~wfithian/)
    -   **Office Hours:** W 3-4, Th 3:30-4:30 in location TBD
    -   **Email:** [wfithian\@berkeley.edu](mailto:wfithian@berkeley.edu)
-   **GSI** Chase Mathis
    -   **Office Hours:** F (time TBD) on [Zoom](link TBD)
    -   **Email:** [cmathis\@berkeley.edu](mailto:cmathis@berkeley.edu)

### Course schedule

-   **Lectures:** Tuesday and Thursday 2-3:30pm, Stanley 106
-   **Tutorial sections:** Time and location TBD
-   **Veterans Day (Wednesday, November 11):** campus holiday. Tuesday and Thursday lectures are unaffected, but:
    - My Wednesday office hours move to Monday, November 9
    - Homework 10 is due Thursday, November 12 instead of Wednesday, giving you an extra day
    - Wednesday tutorial sections are canceled; if Wednesday is your section, you may attend any other section that week
-   **Thanksgiving week:**
    - Tuesday, November 24: lecture 2-3:30pm on Zoom
    - Thursday, November 26: no lecture
    - All other programming canceled: no office hours, homework, quiz, or tutorial
-   **Final exam review:** Friday, December 11, time TBD (Chase's final OH)
-   **Final exam:** Tuesday December 15, 8-11am

### Course communications

-   **Homework solutions** at [bCourses](https://bcourses.berkeley.edu/courses/1557687)
-   **Email policy:** You can email course staff about administrative questions, with "\[Stat 210A\]" in the subject line. *No math* over email, please.
-   [Ed page](https://edstem.org/us/courses/101895/) for announcements and technical discussion (please avoid homework spoilers!)
-   [Gradescope](https://www.gradescope.com/courses/1355311) for turning in homework

## About Stat 210A

### What is the theory of statistics?

Statistics is the study of methods that use data to understand the world. Statistical methods are used throughout the natural and social sciences, in machine learning and artificial intelligence, and in engineering. Despite the ubiquitous use of statistics, its practitioners are perpetually accused of not actually understanding what they are doing. Statistics theory is, broadly speaking, the subject of what exactly we are doing when we apply statistical methods.

While there are many possible ways to analyze data, most (but certainly not all) statistical methods are based on **statistical modeling:** treating the data as a realization of some *random* data-generating process with attributes, usually called *parameters*, that are *a priori* unknown. The goal of the **analyst**, then, is to use the data to draw accurate inferences about these parameters and/or to make accurate predictions about future data. If the modeling has been done well (a very big "if") then these unknown parameters will correspond well to whatever real-world questions initially motivated the analysis. Applied statistics courses like Stat 215A and B delve deeply into questions about how to ensure that the statistical modeling exercise successfully captures something interesting about reality.

In this course we will instead focus on how the analyst can use the data most effectively within the context of a given mathematical setup. We will discuss the structure of statistical models, how to evaluate the quality of a statistical method, how to design good methods for new settings, and the philosophy of Bayesian vs frequentist modeling frameworks. We will cover estimation, confidence intervals, and hypothesis testing, in parametric and nonparametric methods, in finite samples and asymptotic regimes.

### Topics

Statistical decision theory (frequentist and Bayesian), exponential families, point estimation, hypothesis testing, resampling methods, estimating equations and maximum likelihood, empirical Bayes, large-sample theory, high-dimensional testing, multiple testing and selective inference.

### Prerequisites

The course prerequisites are linear algebra, analysis, probability, and statistics. See the [course FAQ](faq.qmd) for more details if you are unsure about your level of preparation.

### Relationship of Stat 210A to other Berkeley courses

Stat 210A focuses on *classical* statistical contexts: inference in finite samples and in fixed-dimensional asymptotic regimes. Stat 210B (for which 210A is a prerequisite) is more technical and covers topics like empirical process theory and high-dimensional statistics.

Berkeley's graduate course on Statistical Learning Theory (CS 281A / Stat 241A) is also very popular and has some overlap in its topics. Roughly speaking, it is more tilted toward "machine learning": it spends more time on topics in predictive modeling (i.e. classification and regression, which are covered in Stat 215A), optimization, and signal processing, but spends less time on inferential questions and (I believe) does not cover topics like hypothesis testing, confidence intervals, and causal inference. Both courses cover estimation and exponential families.

## References

The online notes for this course are self-contained, however it can be helpful to see a different presentation in the following supplementary texts (all links are to public websites or Springer Link):

-   [Keener, *Theoretical Statistics: Topics for a Core Course*, Springer 2010.](http://link.springer.com/book/10.1007%2F978-0-387-93839-4) The textbook that is closest in technical level and presentation style to our course reader.

-   [Lehmann and Casella, *Theory of Point Estimation*, Springer 1998.](http://link.springer.com/book/10.1007%2Fb98854) A highly-detailed reference text that covers much of the estimation material in this course.

-   [Lehmann and Romano, *Testing Statistical Hypotheses*, Springer 2005.](http://link.springer.com/book/10.1007%2F0-387-27605-X) A highly-detailed reference text covering much of the material on testing and confidence estimation.

-   [Hacking, *Probability and Inductive Logic*, Cambridge University Press, 2001.](http://fitelson.org/confirmation/hacking_introduction_to_probability_and_inductive_logic.pdf) A beautifully written book that treats probability and statistics from a philosophical point of view.

-   [Candes, Stats 300C Lecture notes, Stanford 2016.](https://statweb.stanford.edu/~candes/stats300c/lectures.html) The course notes for a great course at Stanford that covers some of the later material in this course.

Undergrad-level review texts for prerequisites:

-   [Axler, *Linear Algebra Done Right*](https://link.springer.com/book/10.1007/978-3-319-11080-6)

-   [Abbott, *Understanding Analysis*](https://link.springer.com/book/10.1007/978-1-4939-2712-8)

-   [Adhikari & Pitman, *Probability for Data Science*](http://prob140.org/textbook/)

## Grading

Your final grade is based on:

-   Homework completion: 10%

-   Tutorial attendance: 10%

-   Tutorial problem correctness: 20%

-   Weekly quizzes: 20%

-   Final exam: 40%

**Weekly homework:** Each week, there will be a problem set with four problems, released on Wednesday, and due by 11:59pm the following Wednesday, with solutions released 15 minutes after. You are welcome to work with each other or consult articles, textbooks, or generative AI, but you are **strongly recommended** to write it up yourself without help. The homework is **graded for completion**, not correctness.

**Tuesday quizzes:** At the beginning of class each Tuesday, beginning September 8, there will be a 10-minute quiz consisting of a short question covering material in a recent lecture.

**Tutorial sections (new this semester):** Beginning the week of September 14, every student will attend a recurring one-hour weekly small-group tutorial section, with graded attendance. You should come prepared to solve problems from the previous week's homework without notes, either orally on the board or on paper. For oral problems, you may be asked questions about your steps as you go. Your odds of scoring well will be higher if you have read and understood the homework solutions. You will be graded both on attendance, and on the correctness of your written and oral problems.

**Excused absence / missed work policy:** We will not offer makeups for missed quizzes or tutorials, or accept late homework submissions. If you cannot make your regularly scheduled tutorial time one week, you are expected to attend a different one. 

We recognize that medical issues, disabilities, or emergencies of various kinds can interfere with students' ability to complete work or attend lectures or tutorials. Please use the [excused absence form](https://docs.google.com/forms/d/e/1FAIpQLScOqW6EpQK9dwHdbP6dPcaHS9trwXY_HHOmLD2cDQys7vPh7A/viewform?usp=header) to request excused absences for quizzes or tutorial sections, or for unsubmitted homeworks; an excused tutorial absence covers both attendance and any graded problem(s) for that week. Excused assignments will not count toward relevant portions of the final grade.

There will be a presumption of valid cause for your first four excused assignment requests; additional requests will be evaluated substantively. To avoid creating a perverse incentive to skip work, students who use $n < 4$ excused assignments will have their worst $4-n$ quizzes, tutorials, or homeworks dropped (with drops chosen to maximize their final grade).

**Academic integrity:** You are expected to abide by the [Berkeley honor code](http://teaching.berkeley.edu/berkeley-honor-code). Violating the collaboration policy, or cheating in any other way, will result in a failing grade for the semester and you will be reported to the University Office of Student Conduct.

## Accommodations

**Students with disabilities:** Please contact me as soon as possible if you need particular accommodations, and we will work out the necessary arrangements.

**Scheduling conflicts:** Please notify me in writing by the second week of the semester about any known or potential extracurricular conflicts (such as religious observances, graduate or medical school interviews, or team activities). I will try my best to help you with making accommodations, but cannot promise them in all cases. In the event there is no mutually-workable solution, you may be dropped from the class.

**Exam accommodations:** If you need accommodations on the final exam due to disability, or unavoidable travel or time conflict, please fill out the exam [exam accommodation form](https://docs.google.com/forms/d/e/1FAIpQLSd6FS1GPJQ5hVy1Q-m6bOn3RW7VK3abmWLwiB5bCNZGjybY2A/viewform?usp=header) **by Friday, September 18** so that I can make arrangements. To ensure exam integrity I much prefer for all students to take the exam on campus at the regularly scheduled time, but will try to work with you if you have an unavoidable conflict.
